spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: number-api
          uri: lb://NUMBER-SERVICE
          predicates:
          - Path=/api/number-service/**
          filters:
          - RewritePath=/api/number-service/(?<segment>.*), /$\{segment}
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG
server:
  port: 8080